Serialize class object
bedrocksystems/tenjint pull request #2
Opened 2020-11-03 18:27 UTC by amanjiofficial

Method to serialize class objects as JSON objects.

2020-11-07 09:42 UTC, pfohjo commented on tenjint/api/api.py
> +            "cpu": self.cpu_num,
Can we take advantage of inheritance here and put the population of the name and timestamp fields in the Event baseclass and populate the cpu field in the CpuEvent baseclass?  The name field can always be set to the class name.

This will reduce some code duplication and ensure all Event objects have a serialize function.

2020-12-10 13:38 UTC, pfohjo requested changes

2020-12-10 13:38 UTC, pfohjo commented on tenjint/event.py
> +        }
I dont think we have a need for this member dict.  Each Event class should implement a serialize function, call the super class's serialize, then add to that before returning.  The Event base class should return "name" and "timestamp", the CpuEvent should add the "cpu_num", and each further subclass can add relevant data.

2020-12-12 09:56 UTC, amanjiofficial commented on tenjint/event.py
> +        }
Updated

2021-01-12 14:08 UTC, pfohjo commented on tenjint/event.py
> +
```
def serialize(self):
    rv = super().serialize()
    rv["cpu_num"] = self.cpu_num
    return rv
```

2021-02-09 13:20 UTC, pfohjo approved these changes

2021-02-09 13:21 UTC, merged